### ISSUE TITLE
HELLO!

### ISSUE THREAD

**Issue by ZZZansian** [Yuri-Vlasqz/3D_Human_Pose_MediaPipe#1]
Thanks for your excellent work!
Could you please show how to get 'Dataset.DELED_RTSP_Cameras.Intrinsic_parameters' ?  I just can not run 'Pose3d_MultiThread_main.py'

**Comment by Yuri-Vlasqz** [comment]
Sorry for the late reply.
The DELED dataset was only used for camera testing (camera matrix a distortion coefficients).
If you use only the [panoptic dataset](http://domedb.perception.cs.cmu.edu/171026_pose3.html),  commenting the lines with DELED and single person dataset should fix the problem
